name: typograph
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: 2.1.8
  cached_network_image: ^0.8.0
  flutter_bloc: ^0.21.0
  path_provider: ^0.5.0+1
  url_launcher: ^5.0.2
  sembast: ^1.15.4
  page_transition: ^1.1.0
  location: ^2.3.5
  shimmer: ^1.0.0
  http: ^0.12.0+2
  encrypt: ">=3.1.0"
  crypto: ">=2.0.6"
  flutter_spinkit: ^4.0.0
  badges: ^1.1.0
  animator: ^1.0.0+1
  flutter_svg: ^0.14.2
  material_search: ^0.2.8
  permission_handler: ^3.2.2
  functional_widget: ^0.7.1
  line_icons: ^0.2.0
  flare_flutter: ^1.5.9
  connectivity: ^0.4.4
  auto_size_text: ^2.1.0
  dynamic_theme: ^1.0.0
  adhara_socket_io: ^0.4.1
  image_picker: ^0.6.1+11
  flutter_lottie_plus: ^0.3.16
  built_value:
  built_collection:


dev_dependencies:
  flutter_test:
    sdk: flutter
  build:
  build_config:
  built_value_generator:
  json_serializable: ^3.0.0
  build_runner: ^1.5.0

flutter:
  uses-material-design: true
